# Generated by Django 5.1.7 on 2025-03-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
