# Generated by Django 5.1.7 on 2025-03-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_checkoutorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutorder',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkoutorder',
            name='payment_mode',
            field=models.CharField(choices=[('UPI', 'UPI'), ('COD', 'Cash on Delivery'), ('CARD', 'Card')], default='COD', max_length=10),
        ),
    ]
